# Gopkg.toml for character
#
# Documentation: <https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md>

required = [
  # All three text table implementations
  "go.pennock.tech/tabular",
  "github.com/apcera/termtables",
  "github.com/olekukonko/tablewriter",
  # Graphing dependencies
  "github.com/kisielk/godepgraph",
  ]

#───────────────────8< Text table implementations >8────────────────────
# Tabular is the one I wrote, to get something clean and powerful enough
# to avoid frustration on my part.  Well, powerful enough.

[[constraint]]
  name = "go.pennock.tech/tabular"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/apcera/termtables"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

#────────────────────────8< Testing & linting >8────────────────────────

[[constraint]]
  branch = "master"
  name = "github.com/liquidgecka/testlib"

[[constraint]]
  branch = "master"
  name = "github.com/kisielk/godepgraph"

#──────────────────────────8< Miscellaneous >8──────────────────────────

# Full-text search, matching characters by parts of their names
[[constraint]]
  branch = "master"
  name = "github.com/argusdusty/Ferret"

# Clipboard copy/paste
[[constraint]]
  branch = "master"
  name = "github.com/atotto/clipboard"

# How wide characters are.  Probably.  We have some overrides.
[[constraint]]
  name = "github.com/mattn/go-runewidth"
  version = "0.0.4"

# Our CLI command definition
[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.4"

# The flags package used by cobra.
[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

# Needed for IDNA (punycode et al)
[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

# Unicode normalization & character set conversions
[[constraint]]
  name = "golang.org/x/text"
  version = "0.3.2"

[prune]
  go-tests = true
  unused-packages = true
